# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: r
r: bioc-release

after_success:
  - Rscript -e 'covr::codecov()'

before_deploy: Rscript -e 'install.packages("devtools"); devtools::install_github("pkgdown")'
deploy:
  provider: script
  script: Rscript -e 'pkgdown::deploy_site_github()'
  skip_cleanup: true
